### ISSUE TITLE
depreciated command

### ISSUE THREAD

**Issue by Ludea** [JonasKruckenberg/tauri-build#209]
https://github.com/JonasKruckenberg/tauri-build/blob/main/.github/workflows/covector-version-or-publish.yml#L42

`set-output` is depreciated

**Comment by jlarmstrongiv** [comment]
Related docs https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by jlarmstrongiv** [comment]
PR https://github.com/JonasKruckenberg/tauri-build/issues/209
