### ISSUE TITLE
Uploading file on Windows 

### ISSUE THREAD

**Issue by Ludea** [JonasKruckenberg/tauri-build#215]
Tauri build correctly artifact
```
     Running candle for "main.wxs"
     Running light to produce D:\a\Sparus\Sparus\src-tauri\target\release\bundle/msi/sparus_0.1.0_x64_en-US.msi
    Finished 1 bundle at:
        D:\a\Sparus\Sparus\src-tauri\target\release\bundle/msi/sparus_0.1.0_x64_en-US.msi
```

When using softprops action-gh-release I get
```
Pattern 'D:\a\Sparus\Sparus\src-tauri\target\release\bundle\msi\sparus_0.1.0_x64_en-US.msi' does not match any files.
🤔 D:\a\Sparus\Sparus\src-tauri\target\release\bundle\msi\sparus_0.1.0_x64_en-US.msi not include valid file.
```

I don't know if it come from tauri-build or softprop action

**Comment by JonasKruckenberg** [comment]
Can't say much without more input (a repro or project to look at) but I just ran the test suite again and it passes without issues (including uploading the msi) so it's most likely an issue with your setup

**Comment by Ludea** [comment]
Log : https://github.com/Ludea/Sparus/actions/runs/4103480208

Workflow : https://github.com/Ludea/Sparus/blob/main/.github/workflows/release.yml

**Comment by Ludea** [comment]
https://github.com/softprops/action-gh-release/issues/280#issuecomment-1322187892 can be relevant

**Comment by Ludea** [comment]
Closing, this issue is not from tauri-build but from softprops action
