### ISSUE TITLE
Create a new 'next' branch to support Tauri 2.0.0-alpha release

### ISSUE THREAD

**Issue by Dreaming-Codes** [JonasKruckenberg/tauri-build#243]
Please create a new 'next' branch in order to support Tauri 2.0.0-alpha.
After the branch is created, you can merge the changes from the following repository: https://github.com/Dreaming-Codes/tauri-build

**Comment by JonasKruckenberg** [comment]
Good idea! There's the [`next`](https://github.com/JonasKruckenberg/tauri-build/tree/nectar) branch now, feel free to open a PR against that branch!

**Comment by JonasKruckenberg** [comment]
Okay you can now use the prerelease version through by specifying `JonasKruckenberg/tauri-build@next`
