### ISSUE TITLE
Support nsis installers for windows

### ISSUE THREAD

**Issue by qu1ck** [JonasKruckenberg/tauri-build#266]
Looks like only msi is recognized as output

https://github.com/JonasKruckenberg/tauri-build/blob/v1.3.0/src/build-project.ts#LL73C1-L73C56

**Comment by JonasKruckenberg** [comment]
What are the output files extensions for nsis installers? I attempted a fix her #289 but I don't have a windows machine to test this

**Comment by qu1ck** [comment]
Exe is the only one I have in the bundle dir but I don't have signing setup so probably your list is fuller.

**Comment by JonasKruckenberg** [comment]
Well then, go ahead an try using this action from the main branch (aka `uses: JonasKruckenberg/tauri-build@main` and see if it works)

**Comment by qu1ck** [comment]
I've been using my fork with similar commit for 3 months, it works for me https://github.com/JonasKruckenberg/tauri-build/commit/5c69c9fdbb4231a738b4a668a2caddf6af45eab8

**Comment by JonasKruckenberg** [comment]
> I've been using my fork with similar commit for 3 months, it works for me [5c69c9f](https://github.com/JonasKruckenberg/tauri-build/commit/5c69c9fdbb4231a738b4a668a2caddf6af45eab8)

Cool it's now supported in the mainline version too :)
