### ISSUE TITLE
Failed to build tauri 1.4 version

### ISSUE THREAD

**Issue by seitbekir** [JonasKruckenberg/tauri-build#273]
I use `src-tauri/tauri.conf.json > tauri > bundle > dev > desktopTemplate` to make my app support files handling in system. Not sure about other features I've used.

Please, update the runner.

**Comment by JonasKruckenberg** [comment]
I know I'm aggressively late here, but its now updated to 1.4.0: https://github.com/JonasKruckenberg/tauri-build/releases/tag/tauri-build-v1.4.0
