### ISSUE TITLE
tar command fails in mac build when productName has spaces

### ISSUE THREAD

**Issue by iJustErikk** [JonasKruckenberg/tauri-build#280]

**Comment by JonasKruckenberg** [comment]
Unsure where you're getting that error from since `tauri-build` does never run tar anywhere. So this must be something specific to you workflow. Gonna close this for now

**Comment by iJustErikk** [comment]
I did not add anything new into the workflow other than using tauri-build. I did the same with the official tauri build, but that did not result in this issue
